UDT-Uplus-Dream-Team/UDT-fe

package-lock.json, src/app/layout.tsx, src/app/recommendation/page.tsx, src/app/recommendation/result/page.tsx, src/components/Ticket/Ticket.tsx, src/components/common/bottom-navbar.tsx
> UDT-75
- Ticket 컴포넌트에서 max, min 사이즈 설정을 통해 뷰포트에 맞춰 동적으로 Ticket 사이즈를 설정할 수 있게 변경
- 일부 스타일 속성 default 값 사용에서 변경
- Ticket component 위치 항상 가운데로 올 수 있도록 변경 
- 가장 작은 size인 iphone SE에 맞춰서 작아진 화면
- 추후에 상세 내용에서 더보기 했을 떄 통일된 스타일 때문에 더보기가 필요 없는 경우에도 줄이거나, 줄거리 파트 제외하고도 공간이 모자란데 더보기가 되지 않는 이유로 컨텐츠가 잘리는 현상 수정 필요
- Results 화면이며, Reroll 아이콘 버튼을 통해서 다른 컨텐츠로 교체 가능, 눈 아이콘 버튼을 통해 'detail' 속성으로 전환 가능
- 드래그를 통해서 옮길 수 있으며, reroll은 1번씩만 가능(총 3장+3장으로 6번)
- 하단의 추가하기 버튼을 통해서 contentId를 저장할 수 있는데, 지금은 console.log로만 되게 했음. 
> Reviewer가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
=> [UDT-75] 추천 페이지 및 엄선된 콘텐츠 페이지 연결 및 개선

.coderabbit.yaml, src/components/common/Skeleton.tsx, src/components/explore/DetailBottomSheetContent.tsx, src/components/explore/ExplorePageCarousel.tsx, src/components/explore/ExplorePageCarouselSkeleton.tsx, src/components/explore/PosterCard.tsx, src/components/explore/PosterCardScrollBox.tsx, src/components/explore/PosterScrollBoxSkeleton.tsx, src/hooks/explore/useGetContentDetails.ts, src/hooks/explore/useGetContentListByBoxType.ts, src/hooks/explore/useGetLatestContents.ts, src/hooks/explore/useGetPopularContents.ts, src/hooks/explore/useGetTodayRecommendContents.ts, src/lib/apis/explore/getContentDetails.ts, src/lib/apis/explore/getLatestContents.ts, src/lib/apis/explore/getPopularContents.ts, src/lib/apis/explore/getTodayContents.ts, src/types/explore/Explore.ts, src/utils/checkImgSrcValidity.ts
UDT-112
- TMI를 영어로 난사하는 codeRabbit의 설정 변경 (`.coderabbit.yaml` 파일 및 사이트에서도 특징 수정)
- API로부터 받아오는 이미지 source의 유효성을 검사하는 `checkImgSrcValidity` 메소드 추가
- “출연진”의 사진을 못 받아왔을 시에 출연진 이름의 맨 첫글자를 `<AvatarFallback>`에 띄우도록 변경
- `PosterCard` 및 `PosterCardScrollBox`에 로딩/오류 시 컴포넌트 처리 추가 (Skeleton UI, ‘다시 불러오기’ UI 추가)
- API의 안정적인 연동을 위해 `useGetPopularContents`, `useGetTodayRecommendContents` Custom Hook과, 그에 연관된 api 함수들 (`getPopularContents`, `getTodayContents`) 수정
**(➕ 7/23 추가사항)**
- `api/contents/recent` api와의 연동을 위해 `getLatestContents`, 그리고 이를 쉽게 사용하도록 해주는 `useGetLatestContents.ts` 수정
-  `useSuspenseQuery`를 사용 중이던 일부 custom Hook들에 대해, `useQuery`를 사용하는 것으로 변경 (해당 변경은 중소 규모의 우리 프로젝트에서 한 파일에서 모든 상태를 관리할 수 있는 `useQuery`가 더 적합하다는 것으로 판단하여 변경된 사안)
- 컴포넌트에서 데이터 로딩 및 에러 발생 시에 Fallback 처리를 위해 `useQuery`의 status …
=> [UDT-112] 탐색 페이지에서의 API 응답을 화면에 자연스럽게 표시하기 위한 리팩토링 진행

src/app/profile/feedbacks/page.tsx, src/app/profile/recommend/page.tsx, src/components/Ticket/Ticket.tsx, src/components/common/Toast.tsx, src/hooks/profile/useDeleteMode.ts, src/hooks/profile/useDeleteToast.ts, src/hooks/profile/usePreferenceHandler.ts, src/lib/apis/profile/recommendService.ts
Udt 122
<ul>
<li>엄선된 컨텐츠 삭제를 위한 api 작성</li>
<li>엄선되 컨텐츠 , 피드백 컨텐츠의 삭제 방법 차이로(contentId , feedbackId) </li>
삭제 모드(useDeleteMode)</strong>를 제네릭 타입으로 정의
<ul>
<li><code>feedbackId</code> 기반 삭제(피드백 콘텐츠)</li>
<li><code>contentId</code> 기반 삭제(엄선된 콘텐츠)</li>
</ul>
<li>실제 삭제 처리의 경우 현재 api 엄선된 데이터는 배열 , 피드백 컨텐츠는 단일 삭제로 삭제 토스트 훅 분기처리<br />
=> 피드백은 시간이 좀....걸린다고 합니다. 추후 변경되는 데로 수정 예정
</li>
<li>티켓 반응형이 아닌 웹 / 모바일 두개로 분리  모바일 320*570 / 웹 400*680 / 글자 크기 수정</li>
<li>더보기의 경우 감독 정보 사라지고 해당 정보 나오게끔 수정</li>
</ul>
https://github.com/user-attachments/assets/4aef1a62-71f7-4cd7-959e-48e1365c33e2
현재 showSimpleToast이 포지션을 센터로 줘도 스타일을 바꿔도 전역 처리를 해봐도? 자꾸 저렇게 치우쳐 나오는데
혹시 이유를 아시는 분 계실까용?
=> [UDT-122] 마이페이지 엄선된 컨텐츠 삭제 api 연동 

src/app/layout.tsx, src/components/common/Toast.tsx, src/hooks/profile/useDeleteToast.ts
UDT-137
- `sonner` 라이브러리를 활용한 Toast 컴포넌트가 화면에 pop-up 될 때, `top-center`(가운데 정렬)되지 않는 문제 수정
- `useDeleteToast` custom Hook에서 "삭제가 완료되었습니다" Toast 관련하여 배경색 및 글자 정렬 변경
Toast 가운데 정렬을 시키기 위한 고난과 역경의 과정..............🥹 집념은 승리한다
https://github.com/user-attachments/assets/5b0a7ba8-575c-4471-a042-dd7ebb851816
- 핵심적으로 최상단 `layout.tsx` 파일에서 `Toaster` 컴포넌트에 `toastOptions` props 값을 넘기니 해결 되었습니다. 이런 방법으로 문제를 해결하긴 했는데, 해당 방법이 다른 CSS 속성에 영향을 줄 수 있는지 검토 부탁드립니다!
=> [UDT-137] sonner 라이브러리를 통해 구현한 toast의 화면 정렬 문제 수정

src/app/recommend/LoadingScreen.tsx, src/app/recommend/RecommendScreen.tsx, src/app/recommend/ResultScreen.tsx, src/app/recommend/StartScreen.tsx, src/components/Ticket/Ticket.tsx, src/components/common/sparkle_background.tsx, src/hooks/recommend/usePostCuratedContents.ts
> UDT-130
- Ticket 컴포넌트가 Result, Recommend Screen에서 모두 반응형으로 사이즈 조정 가능하도록 변경
- ResultScreen에서 Ticket 간의 간격 화면 사이즈, Ticket 사이즈에 맞게 바뀌게 수정
- RecommendScreen 앞에도 LoadingScreen 추가, LoadingScreen에 props를 넘겨 재사용할 수 있도록 변경
- Ticket 이미지 로드 실패 시 poster, backdrop각각 placeholder로 대체 가능하도록 변경
- 모바일/ 개발자 도구를 위한 Touch 애니메이션 관련 메서드 및 스타일 추가
- 스와이프 시 currentIndex가 바로 변경되어 스와이프 애니메이션 도중 다음 컨텐츠의 정보가 표기되는 현상 수정
- 엄선된 컨텐츠 저장 시 409 Conflict response 받을 떄 저장 거부 인터액션 구현 완
> 여기 명시되지 않은 버그 발견 시 바로바로 알려주세요!
=> [UDT-130] Ticket 컴포넌트 반응형 디자인 수정, 모바일/개발자 도구 애니메이션 수정, 스와이프 및 로딩 수정

src/app/survey/page.tsx, src/lib/platforms.ts, src/types/survey/Survey.ts
- 1, 2차 MVP 때는 사용자 Survey를 받을 때, contentID는 받지 않음 -> 구독 OTT 및 장르만 받도록 수정
- `Survey.ts`의 `PostSurveyRequest`에서 contentIds 값은 선택적 필드로 지정 -> 콘텐츠 선택은 "건너뛰기"가 가능하기에 수정한 부분
- lib/platforms.ts 에서 `appleTV`로 맵핑 되어있던 것을 `appleTv`로 변경 (배포 환경에서는 파일 대소문자 구분을 확실하게 해야 하다고 합니다!!)
- 급하게 수정한 부분에 대해서 오류가 있다면 확인해 주시면 감사하겠습니다 :)
=> hotfix: 설문조사(survey) 페이지 데이터 타입 및 종료 시점 일시 변경

src/app/globals.css, src/components/survey/Step2.tsx, src/components/survey/Step3.tsx, src/components/survey/SurveyPosterCard.tsx, src/components/survey/mockContents.ts
- step 3에서 콘텐츠 목록이 안나오고 스켈레톤 ui만 계속 뜨는 문제 해결 (image가 hidden되어있던 문제)
- step2와 step3( 장르, 콘텐츠 목록) 에 스크롤 바 보이도록 변경
- mock data 에서 url 오타 수정 
- 현재 설문조사 step3 에서 콘텐츠 목록을 보여줄 때 장르 불문 랜덤으로 mock data 9개 보여주는 방식인데 step2에서 설문 받은 선호 장르 기반으로 mock data를 보여주는 방식으로 바꿔야 할지 의견 부탁드립니다
=> hotfix: 설문조사 step3에서 콘텐츠 목록 안보이는 문제 해결

src/components/explore/ExplorePageCarousel.tsx, src/components/explore/PosterCardScrollBox.tsx, src/components/explore/PosterCardsGrid.tsx, src/constants/FilterData.ts, src/constants/index.ts, src/hooks/explore/useGetContentListByBoxType.ts, src/hooks/useMutationErrorToast.ts, src/hooks/useQueryErrorToast.ts, src/lib/apis/axiosInstance.ts, src/lib/handleLogout.ts, src/utils/createFilterRequestParam.ts
- `PosterCardsGrid`(필터 선택 후 나오는 그리드) 에서 불러온 정보가 없을 시 "검색 결과가 없습니다" 텍스트 표시
- `PosterCardsGrid` 에서 무한 스크롤 시 "불러오는 중" 텍스트를 화면 가운데에 오도록 배치 수정
- `RATING_OPTIONS` 관련한 정보들에서 명칭 변경 (12세 이상 -> 12세 이상 관람가, 15세 이상 -> 15세 이상 관람가)
- `axiosInstance` 에서 전역 interceptor가 하는 역할로 인해 에러 Toast가 여러 번 뜨는 문제 해결
-  로그아웃을 담당하는 `handleLogout`을 `lib` 폴더에 분리, 각 api 함수에서 로그아웃 로직을 따로 구현하거나, `useQueryErrorToast`에서 불러와 사용하도록 코드 구조 리팩토링
- `useMutation`으로 생성된 Mutation 객체에도 Error 처리와 Error Toast 띄우는 로직을 일원화 하기 위한 `useMutationErrorToast` Hook 추가
- TanStack Query를 사용하는 객체들에 대해, Error 처리를 일원화 하기 위한 `useQueryErrorToast`, `useMutationErrorToast`  Hook에서, 맨 마지막의 retry 에서만 error 처리를 할 수 있도록 로직 수정
필터링 시 검색 결과가 없는 경우, 아래와 같이 텍스트를 pop-up 해줍니다.
그리고 이젠, 에러 토스트 뜨는 것의 중복 처리가 진행되어, 인증 오류(401)를 포함한 모든 상황에서 Toast는 단 한 번만 발생합니다. (api 함수로만 …
=> hotfix: 탐색 페이지 QA 사항 수정

src/app/survey/page.tsx, src/components/survey/Step1.tsx, src/components/survey/Step2.tsx, src/components/survey/mockContents.ts, src/hooks/useErrorToastOnce.ts
- 설문조사 toast error 타입으로 전체 통일
- 설문조사 콘텐츠 mock data 중 이름이 같은 콘텐츠는 1개만 나오도록 중복 제거 (근데 사용 안하게 됨)
- 설문조사 step3 콘텐츠 목록 단계 비활성화
- useErrorToastOnce 라는 새로운 훅 생성 (에러 토스트 중복 방지용) -> error toast 일 경우 toast 가 띄워져 있는 경우에는 에러가 발생해도 toast 가 또다시 나타나지 않고 기존 toast가 사라져야 다음 toast 나타날 수 있도록 변경 
- toast 중 error 옵션인 경우만 해당하는 중복 방지 hook을 만들었는데 괜찮은 방식인지 검토 부탁드립니다.
=> Hotfix: 설문조사 에러 토스트 중복 방지 훅 적용 및 step3 콘텐츠 목록 단계 비활성화로 변경

src/app/globals.css
- `global.css`에서 tailwind `md` 사이즈 640px로 변경
이거야......................
- 왜 `sm`은 안 먹히는지 이유 아시는 분 연락좀
=> hotfix: global.css에서 md 사이즈 수정

src/app/explore/page.tsx, src/app/profile/feedbacks/page.tsx, src/app/profile/recommend/page.tsx, src/components/common/bottom-navbar.tsx, src/components/explore/DetailBottomSheetContent.tsx, src/components/explore/DetailBottomSheetSkeleton.tsx
- `DetailBottomSheetContent` 정보 로딩 시 사용할 `DetailBottomSheetSkeleton` 추가
- `/explore/page.tsx` 화면에서 하단 패딩 및 상단 필터 바 제대로 화면 상단에 고정 안되는 문제 수정
> 여러분들 옆에서 다 지켜보지 않으셨습니까...... 험난한 현장을...............🤸
- 제발 나와라........... 배포 좀 하자..........
- 이상한 부분 있으면 문의 바람 (010-2634-1186)
- 이번에도 똑바로 안되면 유레카 퇴소함
=> hotfix: layout 버그 수정 및 DetailBottomSheetContent 스켈레톤 추가

src/components/profile/MovieCard.tsx, src/components/profile/MovieDetailModal.tsx
> ex) #이슈번호, #이슈번호
1. 모바일 화면에서 좋아요, 싫어요 컨텐트 상세보기 화면 안맞는 상황
=>카드모드와 모달 전체적인 카드 크기 수정 
2. 모달이 띄어 졌을 때 위에 배경 스크롤 되지 않도록 수정
> Reviewer가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
=> Hotfix: 마이페이지 상세보기 카드 모바일 화면에 맞게 수정

src/app/profile/feedbacks/page.tsx, src/app/profile/recommend/page.tsx, src/hooks/profile/useDeleteFeedback.ts, src/hooks/profile/useDeleteToast.ts, src/lib/apis/profile/feedbackService.ts, src/lib/apis/profile/recommendService.ts
UDT-186
- 좋아요/싫어요 피드백 콘텐츠 배열 삭제 기능 구현
- DELETE API 경로를 `/api/users/me/feedbacks` 로 변경
- `axiosInstance.delete()`에 `{ data: { feedbackIds } }` 형식으로 데이터 전달
- `useDeleteFeedback` 훅 및 `useDeleteToast` 통합 처리
- `FeedbackPage`에서도 `RecommendPage`와 동일한 삭제 UI 흐름으로 통일
=> [UDT-186] 피드백 삭제 엔드포인트 변경으로 인한 삭제 api 수정

src/app/explore/page.tsx, src/components/explore/ExplorePageCarousel.tsx, src/components/explore/FilterRadioButtonGroup.tsx, src/components/explore/PosterCardsGrid.tsx
UDT-191
- `PosterCardsGrid`에서, Grid 칸 각각에 카드 정렬이 가운데 정렬 되는 것으로 수정
- `PosterCardsGrid`에서 상태 값(“불러오는 중…”, “검색 결과가 없습니다” 등)이 화면 가운데에 나오지 않는 문제 수정
- `ExplorePageCarousel`에서 잠재적으로 발생할 수 있는 오류에 대비하기 위한 코드 리팩토링
- `FilterRadioButtonGroup`에서 스크롤 시에 화면 상단에 고정 안되는 문제(`sticky` 옵션 적용 안되는 문제) 해결 및 스타일 수정
스크롤 시에 상단의 버튼이 제대로 sticky 되는 것, 그리고 `PosterCardGrid`의 정렬 및 스타일링 똑바로 돌아온 것을 확인할 수 있습니다.
https://github.com/user-attachments/assets/0c9f741f-7ffc-42da-ad40-03db170415bb
- `explore/page.tsx`에서 구성 되었던 레이아웃 형식을, 스크롤 불가능한 최상단 컴포넌트를 따로 하나 빼고, 그 안에서 스크롤 가능한 컨테이너를 또 하나 생성함으로써 `FilterRadioButtonGroup`에서 `sticky` 옵션이 먹히지 않는 문제를 해결했습니다. 해당 레이아웃 구성 방식이 효율적인지 리뷰 부탁드립니다!
- `ExplorePageCarousel`에서 CodeRabbit이 리뷰한 점을 반영해서 리팩토링을 진행했습니다. 해당 리팩토링이 효율적인 방향인지 리뷰 부탁드립니다!
=> [UDT-191] 탐색(Explore) 페이지 QA 사항 2차 수정

src/app/layout-wrapper.tsx, src/app/onboarding/OnboardingClient.tsx, src/app/onboarding/page.tsx
UDT-208
<h2>✅ 온보딩 스타일 변경</h2>
<p><strong>온보딩 단계 상태관리 useState → query param 방식으로 변경</strong></p>
<p>전체 레이아웃 nav바 없을 때 스타일 변경</strong></p>
<h2>✅ 주요 변경사항</h2>
<ul>
<li>기존 <code>useState</code> 기반 <code>started</code>, <code>step</code> 상태 제거</li>
<li>URL query string (<code>?step=0</code>, <code>?step=1</code> ...) 기반으로 단계 관리</li>
<li><code>useSearchParams</code>, <code>router.push()</code>를 사용하여 단계 이동 제어</li>
<li>뒤로가기 / 앞으로가기 시 이전 단계로 자연스럽게 이동 가능</li>
<li>새로고침 시에도 현재 단계 유지</li>
<li><code>StartScreen</code>은 <code>?step</code> query가 없을 때만 노출되도록 분기 처리</li>
<li><code>ProgressDots</code> 및 각 Step 컴포넌트는 그대로 유지 (기존 <code>onNext</code> props 사용 방식 동일)</li>
<li>전체 레이아웃 height: shouldHideBottomNavbar ? '100%' : 'calc(100% - 60px)'로 네비 없을 시 100%처리</li>
</ul>
<p>🔧 <code>useSearchParams</code> 클라이언트 …
=> [UDT-208] 온보딩 query param 수정

package-lock.json, package.json, src/app/admin/page.tsx, src/app/explore/page.tsx, src/components/admin/RequestQueueDashboard.tsx, src/components/admin/SmoothExpandableSidebar.tsx, src/components/explore/ExplorePageCarousel.tsx, src/components/explore/FilterRadioButtonGroup.tsx, src/components/explore/PosterCardScrollBox.tsx, src/components/explore/PosterCardsGrid.tsx, src/components/explore/RepresentativeContentCard.tsx, src/components/ui/dropdown-menu.tsx, src/components/ui/table.tsx
UDT-210
- 관리자(`/admin`) 페이지의 최상단 컴포넌트(`page.tsx`)에 다른 페이지를 오갈 수 있는 `SmoothExpandableSidebar` 추가
- 서버에서의 콘텐츠 수정/삭제/등록 요청들에 대해 배치 처리로 인해 pending 중인 요청 목록을 조회 및 취소할 수 있는 `RequestQueueDashboard` 추가 (현재 수정 중)
- `DetailBottomSheetContent` 등의 컴포넌트에 대해 일부 화면에서 표시될 때 흰색 테두리가 보이는 문제 해결 (해당하는 `Sheet`, `Card` 컴포넌트에 `!border-none`, `!shadow-none` 등의 옵션 추가)
`admin`의 최상단 페이지에 `SmoothExpandableSidebar`를 두고, 동적 헤더, 그리고 사이드바 콘텐츠 선택에 따른 자식 컴포넌트를 갈아 끼는 방식으로 구성되어 있습니다. 데스크톱 기준이며, 아래는 해당 컴포넌트 구현 실제 시연 영상입니다.
https://github.com/user-attachments/assets/f376ff52-a1ce-495f-9c41-a9011d0209e3
- `admin` 페이지의 `page.tsx` 구조를 사이드바 구성과 동적 헤더 구성으로 인해 많이 변경되었습니다. 데스크톱 기준으로 구성되어 있으며, 어드민 페이지의 최상단 `page.tsx`가 효율적으로 구성되어 있는지 리뷰 부탁드립니다.
- `ChildrenComponent`를 맵핑한 다음, 해당하는 컴포넌트를 불러오는 방식으로 구성되어 있습니다. 해당 구조가 효율적인지 리뷰 부탁드립니다. …
=> [UDT-210] 관리자(백오피스) 페이지 최상단 page.tsx 수정 및 사이드 바, 요청 대기열 페이지 수정 + 일부 QA 사항 수정

src/app/survey/SurveyFlow.tsx, src/app/survey/page.tsx, src/components/admin/ContentForm.tsx
UDT-192-refactor/survey-step-to-query-param
- 설문조사 시작 화면 UI 제작
- 설문조사 단계 상태 관리를 쿼리 파라미터 기반으로 전환 (`/survey?step=1` 등)
- 카테고리 변경 시 기존 장르 선택이 초기화되도록 로직 수정
- 설문조사에서 뒤로가기를 눌렀을 때 / 홈으로 이동하고 싶어 설문조사 시작 페이지를 만들었으나 홈으로 이동을 성공하지 못했읍니다.. 이에 대해 의견 있으면 말해주시면 감사하겠습니다
=> [UDT-192] 설문조사 쿼리 파라미터로 변경

src/app/profile/feedbacks/page.tsx, src/app/profile/recommend/page.tsx, src/components/explore/PosterCard.tsx, src/components/explore/PosterCardsGrid.tsx
>Udt 230
1. **PosterCard 컴포넌트에 `ref` 바인딩 가능하도록 수정**
- `forwardRef` 및 `displayName` 지정하여 외부에서 관찰 가능한 요소로 활용 가능하도록 처리
- 무한스크롤 트리거를 카드 자체에 걸 수 있게 되어 UX가 더 자연스러워짐
2. **무한스크롤 동작 방식 개선**
- 기존에는 `div` 요소에만 `ref`를 걸어 리스트 마지막에서 API 요청을 트리거함
- → 자연스럽지 못하고 스크롤이 멈춘 뒤에야 새 데이터가 로드되는 UX 문제가 있었음
- **수정 후**: 마지막에서 8번째 카드(`triggerIndex`)에 `ref`를 걸어 IntersectionObserver가 더 일찍 작동되도록 개선
- → 사용자가 리스트를 스크롤하면서 *끊김 없이 콘텐츠가 이어지도록* UX 향상
3. **적용된 페이지**
- `/explore`: ExplorePage → `PosterCardsGrid`에 `ref` 위치 변경
- `/profile/feedback`: FeedbackPage → `PosterCard`에 `ref` 적용
- `/profile/recommend`: RecommendPage → 동일한 방식으로 개선
- 각 페이지마다 공통적으로 `Math.max(contents.length - 8, 0)` 로 트리거 카드 지정
4. **삭제모드 UX 개선**
- 삭제모드 상태에서 탭 전환 시, `useEffect`로 `handleCancelDeleteMode()` 자동 호출되도록 처리
- 사용자 실수로 인한 혼란 방지
5. **로딩 중인 상태에 대한 시각적 안내 …
=> [UDT-230] 콘텐츠 무한스크롤 자연스럽게 개선 및 삭제모드 UX 향상

src/app/explore/page.tsx, src/components/explore/PosterCard.tsx
UDT-241
- 탐색 페이지 최상단 `page.tsx`에서 가로 스크롤 방지를 위해서 "나머지 모든 콘텐츠가 스크롤되는 영역"에 대해서 `overflow-x-hidden` 옵션  추가
- `PosterCard` 컴포넌트 속 `<Image>`에 대해, `onLoadingComplete` 대신 `onLoad` property 활용 (depercated 된 property 사용 지양을 위함)
`onLoadingComplete` 대신 `onLoad` 프로퍼티를 사용하니, 경고 로그가 무지막지하게 떴던 것이 말끔해 해결되었습늬다^^
- 혹여나 추가적으로 탐색 페이지에서 문제가 발생하는 점이 있다면 말씀해 주세요!
=> [UDT-241] 탐색 페이지에서 가로 스크롤 방지 및 PosterCard에서 <Image> 컴포넌트에 대해 onLoad property로 변경

src/components/admin/ContentDetail.tsx, src/components/admin/ContentForm.tsx, src/components/admin/ContentFormSections/BasicInfo.tsx, src/components/admin/ContentFormSections/CastInfo.tsx, src/components/admin/ContentFormSections/DetailedInfo.tsx, src/components/admin/ContentFormSections/DirectorInfo.tsx, src/components/admin/ContentFormSections/PlatformInfo.tsx, src/components/admin/bulkPersonRegistration.tsx, src/components/admin/dialogs/actorSearchDialog.tsx, src/components/admin/dialogs/directorSearchDialog.tsx, src/components/common/Toast.tsx, src/hooks/admin/usePostCasts.ts, src/hooks/admin/usePostDirectors.ts, src/hooks/admin/usePostUploadImages.ts
UDT-229-feat/admin-bulk-person-create
- 우측 탭 - 인물 등록 탭 (여러 명의 배우, 감독 일괄 등록 할 수 있는) 구현
- 이미지 업로드, 새 배우 등록, 새 감독 등록 시 성공 toast랑 에러 toast try-catch 문 안에서 수행하도록 변경하였습니다.
- 기존의 contentform 파일 (콘텐츠 등록 폼) 을 ContentFormSections 포더 아래에 5개의 파일 (BasicInfo, DetailedInfo, CastInfo, DirectorInfo, PlatformInfo) 로 분리하여 가독성을 높였습니다. 
화면녹화 했는데 왜 자꾸 내거 동영상 올리면 검은화면만 나오고 안나오는지 속상.,
> Reviewer가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
=> [UDT-229] 관리자 페이지 콘텐츠 관리 중 인물 등록 탭 구현
